### ISSUE TITLE
Create bash script

### ISSUE THREAD

**Issue by arturpriz** [Revers32/testrepo#1]
Create bash script that will generate any type of data continually and send it to log file.

**Comment by Revers32** [comment]
Script is done. (https://github.com/Revers32/testrepo/compare/Task1?expand=1) Please review @arturpriz

**Comment by Revers32** [comment]
Updated script (https://github.com/Revers32/testrepo/pull/2/commits/cfedfe93ff586314bae107efc05d8bb3a9f94942) . Please review @arturpriz

**Comment by Revers32** [comment]
https://github.com/Revers32/testrepo/pull/2/files Updated
